#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 14 16:47:48 2020

@author: paul
"""

import sys
from pylab import *
from random import randint


figure (figsize=(10,10))    #graph window: big implies zoom-into graph

# play with these two
particles=100
N=100

boundary=particles/2

atoms=ones([particles,2])*boundary/2     # 'particles' atoms at centre of square

line,=plot(atoms[:,0],atoms[:,1],'ro')      # 'ro': red circle markers
xlim(0,boundary)
ylim(0,boundary)

draw()
savefig("initial.png")


for i in range(N):
    for j in range(particles):    # go through all atoms
        # move (or not) in x or y direc
        atoms[j,0]+=randint(-1,1)
        atoms[j,1]+=randint(-1,1)
        
        #check for boundary collision     !make these according to var particles
        x,y=(atoms[j,0],atoms[j,1])
        if x==boundary:
            atoms[j,0]=boundary-2       #  !note this scale... 2 is just an arbitrary number to prevent spilling over
        elif x==0:
            atoms[j,0]=2
        if y==boundary:
            atoms[j,1]=boundary-2
        elif y==0:
            atoms[j,1]=2
        
    line.set_xdata(atoms[:,0])
    line.set_ydata(atoms[:,1])
    draw()
    savefig("final.png")
   
            

            
